language: C
sudo: false
env:
before_install:
  - export TERM=dumb
  - wget -q --timeout=600 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  - md5sum android-ndk-r10e-linux-x86_64.bin #| grep 6c1d7d99f55f0c17ecbcf81ba0eb201f
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - rm android-ndk-r10e-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export ANDROID_NDK_ROOT=`pwd`/android-ndk-r10e
  - export PATH=$PATH:${ANDROID_NDK_HOME}
script:
  - bash ./build-libssl.sh
after_script:
  - find
