language: C
env:
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y libgd2-xpm ia32-libs ia32-libs-multiarch p7zip
  - sudo apt-get install -qq -y xutils-dev 
  - wget -q --timeout=120 http://dl.google.com/android/ndk/android-ndk-r9d-linux-x86.tar.bz2 -O ndk.tar.bz2
  - md5sum ndk.tar.bz2
  - tar -xf ndk.tar.bz2
  - rm ndk.tar.bz2
  - export ANDROID_NDK_ROOT=$(pwd)/android-ndk-r9d
script:
  - ./build-libssl.sh
