language: C
sudo: false
env:
before_install:
  - export TERM=dumb
  - wget -q --timeout=600 http://dl.google.com/android/repository/android-ndk-r11b-linux-x86_64.zip
  - md5sum android-ndk-r11b-linux-x86_64.zip #| grep 6c1d7d99f55f0c17ecbcf81ba0eb201f
  - unzip -q ./android-ndk-r11b-linux-x86_64.zip 
  - rm android-ndk-r11b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r11b
  - export ANDROID_NDK_ROOT=`pwd`/android-ndk-r11b
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - pwd
script:
  - pwd
  - bash ./build-libssl.sh
after_script:
  - find include
  - find lib
